title: A Brief Intro to Web Design

baseurl: ""
url: "http://yourdomain.com"

repo_url: "https://github.com/allejo/Intro-To-Web"
repo_branch: master

# Build settings
markdown: kramdown

collections:
  lessons:
    output: true
    permalink: /book/:path/
