title: A Brief Intro to Web Design

baseurl: "/Intro-To-Web"
url: "http://yourdomain.com"

repo_url: "https://github.com/allejo/Intro-To-Web"
repo_branch: master

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true

collections:
  lessons:
    output: true
    permalink: /book/:path/

defaults:
  - scope:
      path: ""
      type: lessons
    values:
      layout: post

assets:
  bootstrap: https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css
  fontawesome: https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css